- name: Install apt-packages
  ansible.builtin.apt:
    name: 'apt-transport-https'
    state: present

- name: Install InfluxDB packages
  ansible.builtin.apt:
    name: influxdb
    state: present
    update_cache: true

- name: Start the InfluxDB service
  ansible.builtin.service:
    name: influxdb
    state: started

- name: Wait a few seconds for InfluxDB to start
  ansible.builtin.pause:
    seconds: 5

- name: Install influxdb-client
  ansible.builtin.apt:
    name: influxdb-client
    state: present
    update_cache: true

- name: Create database
  ansible.builtin.command: /usr/bin/influx -execute 'CREATE DATABASE gondul'