# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-02-22T18:10:42+00:00

from __future__ import annotations

from datetime import datetime
from ipaddress import IPv4Address, IPv6Address
from typing import Any

from pydantic import BaseModel, Field


class ConfigData(BaseModel):
    sitename: str | None = Field(None, title='Sitename')
    publicvhost: str | None = Field('public-gondul.tg.no', title='Publicvhost')
    public: bool | None = Field(False, title='Public')
    shortname: str | None = Field('tg25', title='Shortname')


class DeviceManagement(BaseModel):
    sysname: str | None = Field('e1-1', title='Sysname')
    serial: str | None = Field(None, title='Serial')
    platform: str | None = Field(None, title='Platform')
    mgmt_v4_addr: IPv4Address | None = Field(None, title='Mgmt V4 Addr')
    mgmt_v6_addr: IPv6Address | None = Field(None, title='Mgmt V6 Addr')
    mgmt_vlan: str | None = Field(None, title='Mgmt Vlan')
    traffic_vlan: str | None = Field(None, title='Traffic Vlan')
    last_updated: str | None = Field(None, title='Last Updated')
    distro_name: str | None = Field(None, title='Distro Name')
    distro_phy_port: str | None = Field(None, title='Distro Phy Port')


class DevicesManagement(BaseModel):
    switches: dict[str, DeviceManagement] = Field(..., title='Switches')
    time: int | None = Field(None, title='Time')
    hash: str | None = Field(None, title='Hash')


class Network(BaseModel):
    name: str | None = Field('switches-mgmt', title='Name')
    vlan: int | None = Field(1337, title='Vlan')
    tags: list[str] | None = Field([], title='Tags')
    subnet4: str | None = Field('198.51.100.0/24', title='Subnet4')
    subnet6: str | None = Field('2001:db8:5b96::/64', title='Subnet6')
    gw4: IPv4Address | None = Field('198.51.100.1', title='Gw4')
    gw6: IPv6Address | None = Field('2001:db8:5b96::1', title='Gw6')


class Networks(BaseModel):
    networks: dict[str, Network] = Field(..., title='Networks')
    time: int | None = Field(None, title='Time')
    hash: str | None = Field(None, title='Hash')


class OplogBase(BaseModel):
    id: int | None = Field(None, title='Id')
    time: datetime | None = Field('2026-02-22T18:08:17.944869Z', title='Time')
    username: str | None = Field(None, title='Username')
    systems: str | None = Field(None, title='Systems')
    message: str = Field(..., title='Message')


class OplogCreate(BaseModel):
    username: str | None = Field(None, title='Username')
    systems: str | None = Field(None, title='Systems')
    message: str = Field(..., title='Message')


class PingData(BaseModel):
    latency4: float | None = Field(..., description='In milliseconds', title='Latency4')
    latency6: float | None = Field(..., description='In milliseconds', title='Latency6')
    age4: float | None = Field(..., description='In seconds', title='Age4')
    age6: float | None = Field(..., description='In seconds', title='Age6')


class Placement(BaseModel):
    x: int = Field(..., title='X')
    y: int = Field(..., title='Y')
    height: int = Field(..., title='Height')
    width: int = Field(..., title='Width')


class PublicDevice(BaseModel):
    distro_name: str | None = Field(None, title='Distro Name')
    tags: list[str] | None = Field([], title='Tags')
    placement: Placement | None = None


class PublicDevices(BaseModel):
    switches: dict[str, PublicDevice] = Field(..., title='Switches')
    time: int | None = Field(None, title='Time')
    hash: str | None = Field(None, title='Hash')


class Stats(BaseModel):
    misc: dict[str, Any] | None = Field(None, title='Misc')
    ports: dict[str, Any] | None = Field(None, title='Ports')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class Config(BaseModel):
    config: ConfigData
    time: int | None = Field(None, title='Time')
    hash: str | None = Field(None, title='Hash')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class Oplog(BaseModel):
    oplog: list[OplogBase] = Field(..., title='Oplog')
    time: datetime | None = Field('2026-02-22T18:08:17.946569Z', title='Time')
    hash: str | None = Field(None, title='Hash')


class Ping(BaseModel):
    switches: dict[str, PingData] = Field(..., title='Switches')
    time: int | None = Field(None, title='Time')
    hash: str | None = Field(None, title='Hash')


class Snmp(BaseModel):
    snmp: dict[str, Stats] = Field(..., title='Snmp')
    time: int | None = Field(None, title='Time')
    hash: str | None = Field(None, title='Hash')
