#! /usr/bin/perl
# vim:ts=8:sw=8

use CGI qw(fatalsToBrowser);
use DBI;
use lib '/opt/gondul/include';
use nms;
use nms::web;
use strict;
use warnings;
use Data::Dumper;

$nms::web::cc{'max-age'} = "5";
$nms::web::cc{'stale-while-revalidate'} = "30";

my $q2 = $nms::web::dbh->prepare('select name, vlan, networks.tags, switches.sysname as router, subnet4, subnet6, gw4, gw6 from networks left join switches on switches.switch = networks.router');

$q2->execute();
while (my $ref = $q2->fetchrow_hashref()) {
	my $name = $ref->{'name'};
	$nms::web::json{'networks'}{$ref->{'name'}} = $ref;
	my $data = JSON::XS::decode_json($ref->{'tags'});
	$nms::web::json{'networks'}{$ref->{'name'}}{'tags'} = $data;
}

finalize_output();
