#! /usr/bin/perl
# vim:ts=8:sw=8

use lib '/opt/gondul/include';
use nms::web;
use strict;
use warnings;

my @dirs = ("/opt/gondul/web/templates","/opt/gondul/data/templates");

foreach my $template_dir (@dirs) {
opendir (DIR, $template_dir) or next;
while (my $file = readdir(DIR)) {
        next if ($file =~ m/^\./);
        my %meh;
        $meh{'file'} = $file;

        push @{$nms::web::json{'templates'}},\%meh;
}
}
nms::web::finalize_output();
