#! /usr/bin/perl
# vim:ts=8:sw=8

use DBI;
use lib '/opt/gondul/include';
use nms;
use nms::web;
use strict;
use warnings;
use Data::Dumper;

$nms::web::cc{'max-age'} = "3600";

my $hostname = $ENV{'HTTP_HOST'} || "";
my $q2 = $nms::web::dbh->prepare('select id, publicvhost, shortname, data from config order by id desc limit 1;');

$q2->execute();
$nms::web::json{'config'}{'data'} = 0;
$nms::web::json{'config'}{'shortname'} = "notset";
$nms::web::json{'config'}{'publicvhost'} = "notset";
while (my $ref = $q2->fetchrow_hashref()) {
	$nms::web::json{'config'} = $ref;
	$nms::web::json{'config'}{'data'} = JSON::XS::decode_json($ref->{'data'});
	if ($ref->{'publicvhost'} eq $hostname) {
		$nms::web::json{'config'}{'public'} = "true";
	} else {
		$nms::web::json{'config'}{'public'} = "false";
	}
}

finalize_output();
