"""empty message

Revision ID: 4e556e723de0
Revises: 106dece647f0
Create Date: 2026-02-19 21:41:07.395469

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4e556e723de0'
down_revision = '106dece647f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oplog', 'time',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using='to_timestamp(time)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oplog', 'time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using='extract(epoch from time)')
    # ### end Alembic commands ###
