- name: Install front-packages
  ansible.builtin.apt:
    name: [
      'libcapture-tiny-perl',
      'libcommon-sense-perl',
      'libdata-dumper-simple-perl',
      'libdbd-pg-perl',
      'libdbi-perl',
      'libdigest-perl',
      'libgd-perl',
      'libgeo-ip-perl',
      'libhtml-parser-perl',
      'libhtml-template-perl',
      'libjson-perl',
      'libjson-xs-perl',
      'libnetaddr-ip-perl',
      'libnet-cidr-perl',
      'libnet-ip-perl',
      'libnet-oping-perl',
      'libnet-rawip-perl',
      'libsnmp-perl',
      'libsocket6-perl',
      'libsocket-perl',
      'libswitch-perl',
      'libtimedate-perl',
      'perl',
      'perl-base',
      'perl-modules',
      'libfreezethaw-perl',
      'apache2',
      'libxml2-dev',
      'build-essential',
      'cpanminus',
      'apt-transport-https',
      'python3-netaddr',
      'python3-flask']
    state: present

- name: Install InfluxDB module
  community.general.cpanm:
    name: AnyEvent::InfluxDB

- name: Make apache listen on port 8080
  ansible.builtin.lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8080" state=present
  notify: Restart apache

- name: Add Apache2 Module
  ansible.builtin.apache2_module:
    state: present
    name: cgid
  notify: Restart apache

- name: Enable gondul-config
  ansible.builtin.copy:
    dest: /etc/apache2/sites-enabled/gondul.conf
    src: apache-virtualhost.conf
  notify: Restart apache

- name: Disable default Apache site
  ansible.builtin.command: a2dissite 000-default
  ignore_errors: true
  notify: Restart apache

- name: Ensure Varnish is installed.
  ansible.builtin.apt:
    name: "varnish"
    state: present

- name: Ensure folder varnish.service.d exists
  ansible.builtin.file:
    path: /etc/systemd/system/varnish.service.d/
    state: directory
    mode: 0755

- name: Change varnish service.d
  ansible.builtin.copy:
    dest: /etc/systemd/system/varnish.service.d/customexec.conf
    src: varnish.service
  notify:
    - Reload systemd

- name: Copy varnish-acl config
  ansible.builtin.copy:
    dest: /etc/varnish/auth.vcl
    src: auth.vcl
  notify: Restart apache

- name: Copy varnish config
  ansible.builtin.copy:
    dest: /etc/varnish/default.vcl
    src: varnish.vcl
  notify: Restart apache

- name: Add systemd service file for gondul-template
  ansible.builtin.copy:
    dest: /etc/systemd/system/gondul-template.service
    src: gondul-template.service
  notify: Restart gondul-template