#! /usr/bin/perl
# vim:ts=8:sw=8
use lib '/opt/gondul/include';
use utf8;
use nms;
use nms::web qw($dbh db_safe_quote get_input finalize_output);

use strict;
use warnings;

my %input = %{JSON::XS::decode_json(get_input())};

my ($q,$check);
my $metric = $dbh->prepare("INSERT INTO metrics (src,metadata,data) VALUES(?,?,?)");

$nms::web::cc{'max-age'} = '0';
$nms::web::cc{'stale-while-revalidate'} = '0';
$nms::web::json{'state'} = 'ok';

foreach my $entry (@{$input{'data'}}) {
	$metric->execute($input{'src'},JSON::XS::encode_json($input{'metadata'}),JSON::XS::encode_json($entry));
}
finalize_output();
