#! /usr/bin/perl
# vim:ts=8:sw=8
use lib '../../../../include';
use utf8;
use nms;
use nms::web qw($dbh db_safe_quote get_input finalize_output);

use strict;
use warnings;

my $in = get_input();
my %tmp = %{JSON::XS::decode_json($in)};

my $id = $dbh->quote($tmp{'comment'});
my $state = $dbh->quote($tmp{'state'});

my $q = $nms::web::dbh->prepare("UPDATE switch_comments SET state = " . $state . " WHERE id = " . $id . ";");
$q->execute();

$nms::web::cc{'max-age'} = '0';
$nms::web::cc{'stale-while-revalidate'} = '0';
$nms::web::json{'state'} = 'ok';

print "X-ban: /api/read/comments\n";
finalize_output();
