#! /usr/bin/perl
# vim:ts=8:sw=8
use lib '/opt/gondul/include';
use utf8;
use nms;
use nms::web qw($dbh db_safe_quote get_input finalize_output);

use strict;
use warnings;

my $in = get_input();
my %tmp = %{JSON::XS::decode_json($in)};

my $q = $nms::web::dbh->prepare("INSERT INTO config (publicvhost,shortname,data) VALUES(?,?,?);");
$q->execute($tmp{'publicvhost'},$tmp{'shortname'},JSON::XS::encode_json($tmp{'data'}));

$nms::web::cc{'max-age'} = '0';
$nms::web::cc{'stale-while-revalidate'} = '0';
$nms::web::json{'state'} = 'ok';

print "X-ban: /api/public/config\n";
finalize_output();
