#! /usr/bin/perl
# vim:ts=8:sw=8

#use CGI qw(fatalsToBrowser);
use DBI;
use lib '/opt/gondul/include';
use nms;
use nms::web qw(%get_params %json finalize_output get_input $dbh);
use nms::util qw(guess_placement);
use strict;
use warnings;
use JSON;
use Data::Dumper;

$nms::web::cc{'max-age'} = "0";

my $in = get_input();
my @tmp = @{JSON::XS::decode_json($in)};

my @added;
my @dups;

my $sth = $nms::web::dbh->prepare("SELECT name FROM networks WHERE name=?");


my @fields = ('name','last_updated','subnet4','subnet6','gw4','gw6','routing_point','vlan','tags');

foreach my $tmp2 (@tmp) {
	my %network = %{$tmp2};
	my $affected = 0;
	my %template = ();
	map { $template{$_} = 'DEFAULT' } @fields;
	if (not defined($network{'name'})) {
		next;
	}

	$sth->execute( $network{'name'});
	while ( my @row = $sth->fetchrow_array ) {
		$affected += 1;
	}

	if ($affected == 0) {

		map {
			if (defined ($template{$_})) {
					$template{$_} = $dbh->quote($network{$_});
			}
		} keys %network;


		$nms::web::dbh->do("INSERT INTO NETWORKS (name, last_updated, subnet4, subnet6, routing_point, gw4, gw6, vlan, tags)  VALUES ($template{'name'}, $template{'last_updated'}, $template{'subnet4'}, $template{'subnet6'}, $template{'routing_point'}, $template{'gw4'}, $template{'gw6'}, $template{'vlan'}, $template{'tags'});");
		push @added, $network{'name'};
	} else {
		if (defined($network{'tags'})) {
			$network{'tags'} =~ s/'/"/g;
		}
		my @set;
		map {
			if (defined($template{$_})) {
				push @set, "$_=" . $dbh->quote($network{$_});
			}
		} keys %network;
		$nms::web::dbh->do("UPDATE networks SET " . join(", ", @set) . "WHERE name=" . $dbh->quote($network{'name'}) . ";");
		push @dups, $network{'name'};
	}
}
$json{'networks_addded'} = \@added;
$json{'networks_updated'} = \@dups;

print "X-ban: /api/.*networks.*\n";
finalize_output();
