#! /usr/bin/perl
# vim:ts=8:sw=8
use lib '/opt/gondul/include';
use utf8;
use nms::web qw($dbh db_safe_quote get_input finalize_output);
use strict;
use warnings;

my $in = get_input();
my %tmp = %{JSON::XS::decode_json($in)};

my $user = $tmp{'user'} || $ENV{'REMOTE_USER'} || "undefined";

my $q = $nms::web::dbh->prepare("INSERT INTO oplog (username, systems, log) values (?,?,?);");
$q->execute($user, $tmp{'systems'}, $tmp{'log'});

$nms::web::cc{'max-age'} = '0';
$nms::web::cc{'stale-while-revalidate'} = '0';
$nms::web::json{'state'} = 'ok';

print "X-ban: /api/read/oplog\n";
finalize_output();
